name: Test Python
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Chekcout code
        uses: actions/checkout@v2
      - name: Test
        run: |
          cd python
          python -m unittest
